version: '3'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - ./dev/grafana_db:/var/lib/grafana grafana/grafana
  secret:
    build:
      context: .
    restart: on-failure
    networks:
      localnet:
        ipv4_address: 172.30.0.10
    env_file: ./dev/.env
  nginx:
    image: nginx:1.15
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./dev/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - localnet
    depends_on:
      - secret
  postgres:
    image: postgres:10
    networks:
      - localnet
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - PGDATA=/pgdata
    volumes:
      - ./dev/db/dbdata:/var/lib/postgresql/db-data
      - ./dev/db/init.sql:/docker-entrypoint-initdb.d/init.sql
networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
