{
 "title": "Secret dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Requests count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (type) (secret_group_secret_service_request_count{method=\"create\"})",
     "legendFormat": "CREATE request count"
    },
    {
     "expr": "sum by (type) (secret_group_secret_service_request_count{method=\"get\"})",
     "legendFormat": "GET request count"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{group=\"secret\",instance=\"167.71.168.236:80\",job=\"secret\"}",
     "legendFormat": "Routines number"
    }
   ]
  },
  {
   "title": "POST secret request latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (le) (rate(secret_group_secret_service_request_latency_microseconds_bucket{method=\"create\"}[5m]))\n)",
     "legendFormat": "50% quantile"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (rate(secret_group_secret_service_request_latency_microseconds_bucket{method=\"create\"}[5m]))\n)",
     "legendFormat": "95% quantile"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le) (rate(secret_group_secret_service_request_latency_microseconds_bucket{method=\"create\"}[5m]))\n)",
     "legendFormat": "99% quantile"
    }
   ]
  },
  {
   "title": "Memory stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{group=\"secret\",instance=\"167.71.168.236:80\",job=\"secret\"}",
     "legendFormat": "Allocated memory"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{group=\"secret\",instance=\"167.71.168.236:80\",job=\"secret\"}",
     "legendFormat": "GC memory"
    }
   ]
  },
  {
   "title": "GET secret request latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (le) (rate(secret_group_secret_service_request_latency_microseconds_bucket{method=\"get\"}[5m]))\n)",
     "legendFormat": "50% quantile"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (rate(secret_group_secret_service_request_latency_microseconds_bucket{method=\"get\"}[5m]))\n)",
     "legendFormat": "95% quantile"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le) (rate(secret_group_secret_service_request_latency_microseconds_bucket{method=\"get\"}[5m]))\n)",
     "legendFormat": "99% quantile"
    }
   ]
  }
 ]
}